# Generated by Django 4.2.10 on 2024-04-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettoken',
            name='TOKEN',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
