# Generated by Django 4.2.10 on 2024-04-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_gettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesabha',
            name='code_hesab',
            field=models.PositiveIntegerField(unique=True, verbose_name='کد حساب کل'),
        ),
        migrations.AlterField(
            model_name='moein',
            name='hesabha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hesabha', to_field='code_hesab'),
        ),
    ]
