# Generated by Django 4.2.10 on 2024-04-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_hesabha_code_hesab_alter_moein_hesabha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moein',
            name='code_hesab',
            field=models.PositiveIntegerField(unique=True, verbose_name='کد حساب معین'),
        ),
        migrations.AlterField(
            model_name='tafsili',
            name='code_hesab',
            field=models.PositiveIntegerField(unique=True, verbose_name='کد حساب معین'),
        ),
        migrations.AlterField(
            model_name='tafsili',
            name='moein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.moein', to_field='code_hesab'),
        ),
    ]
