# Generated by Django 4.2.10 on 2024-04-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_moein_code_hesab_alter_tafsili_code_hesab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesabha',
            name='name_hesab',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='moein',
            name='name_hesab',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tafsili',
            name='name_hesab',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
