# Generated by Django 4.2.10 on 2024-04-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_category_asnad'),
    ]

    operations = [
        migrations.AddField(
            model_name='asnad',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
