# Generated by Django 4.2.10 on 2024-04-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_asnad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asnad',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
