# Generated by Django 4.2.10 on 2024-04-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asnad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asnad', to='accounts.category'),
        ),
    ]
