# Generated by Django 4.2.10 on 2024-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_asnad_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
