# Generated by Django 4.2.10 on 2024-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_category_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lisence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
