# Generated by Django 4.2.10 on 2024-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_lisence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lisence',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='لایسنس'),
        ),
    ]
