# Generated by Django 5.0.6 on 2024-09-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_timer',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
