# Generated by Django 5.0.6 on 2024-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_first_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ai_sanad',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
