# Generated by Django 5.1.1 on 2024-10-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_category_ai_sanad'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tafsili',
            name='code_hesab',
            field=models.PositiveIntegerField(unique=True, verbose_name='کد حساب تفصیلی'),
        ),
    ]
