# Generated by Django 5.1.1 on 2024-10-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customuser_first_login_alter_tafsili_code_hesab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesabha',
            name='code_hesab',
            field=models.PositiveIntegerField(verbose_name='کد حساب کل'),
        ),
        migrations.AlterField(
            model_name='moein',
            name='code_hesab',
            field=models.PositiveIntegerField(verbose_name='کد حساب معین'),
        ),
        migrations.AlterField(
            model_name='moein',
            name='hesabha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hesabha'),
        ),
        migrations.AlterField(
            model_name='tafsili',
            name='moein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.moein'),
        ),
    ]
