# Generated by Django 5.1.1 on 2024-10-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_hesabha_code_hesab_alter_moein_code_hesab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tafsili',
            name='code_hesab',
            field=models.PositiveIntegerField(verbose_name='کد حساب تفصیلی'),
        ),
    ]
