# Generated by Django 5.1.1 on 2024-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_tafsili_code_hesab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesabha',
            name='name_hesab',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='moein',
            name='name_hesab',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tafsili',
            name='name_hesab',
            field=models.CharField(max_length=200),
        ),
    ]
