# Generated by Django 4.2.10 on 2024-04-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
