# Generated by Django 4.2.10 on 2024-04-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_email_alter_order_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
