# Generated by Django 4.2.10 on 2024-04-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_mail',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
